### PR TITLE
Part 1 assignment

### PR DESCRIPTION
**Pull request by CurtisCY**
Part 1 assignment
http://54.168.103.229:3000/api/attractions?page=1
http://54.168.103.229:3000/api/attractions?page=0&keyword=藝術
http://54.168.103.229:3000/api/attraction/100
黃晟瑜 Discord: Curtis

### CODE REVIEW

**Comment by cwpeng** [comment]
1. images field should be an array containing image URLs separately, not a single string.
2. response format of http://54.168.103.229:3000/api/attraction/10 is incorrect.

Fix issues and leave comment for me to review again.

**Comment by CurtisCY** [comment]
Hi PengPeng,

Thank you for your review. I have modified the data type of my parameters spotId, spotLatitude and spotLongitude to int and float. Also, I have used an array to place all my image URL separately. If there is something still missing or implemented in wrong way, please kindly let me know.

http://54.168.103.229:3000/api/attractions?page=1
http://54.168.103.229:3000/api/attractions?page=0&keyword=藝術
http://54.168.103.229:3000/api/attraction/100

Thank you.

Curtis

**Comment by cwpeng** [comment]
Not fix.

1. format of "images" field should be ["URL1", "URL2"].
2. response format of http://54.168.103.229:3000/api/attraction/10 is incorrect, still.

If you cannot get my point, feel free to message/talk to me directly.

**Comment by CurtisCY** [comment]
Fix:
1. format of images changes to ["URL1","URL2",...]
2. /api/attractions and /api/attraction are different API endpoint. Change /api/attraction format like below
/api/attractions format "data":[{},{},{}....]
/api/attraction format "data": {}


http://54.168.103.229:3000/api/attractions?page=1
http://54.168.103.229:3000/api/attractions?page=0&keyword=藝術
http://54.168.103.229:3000/api/attraction/100

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
